stages: 
    data_ingestion:
      cmd: python src/IRIS_MLops/pipeline/stage01_data_ingestion.py
      deps:
        - src/IRIS_MLops/pipeline/stage01_data_ingestion.py
        - config/config.yaml
      outs:
        - artifacts/data_ingestion/IRIS.csv

    data_validation:
      cmd: python src/IRIS_MLops/pipeline/stage02_data_validation.py
      deps:
        - src/IRIS_MLops/pipeline/stage01_data_ingestion.py
        - src/IRIS_MLops/pipeline/stage02_data_validation.py
      outs:
        - artifacts/data_validation/status.txt  

    data_transformation:
      cmd: python src/IRIS_MLops/pipeline/stage03_data_transformation.py
      deps:
        - src/IRIS_MLops/pipeline/stage01_data_ingestion.py
        - src/IRIS_MLops/pipeline/stage03_data_transformation.py
      outs:
        - artifacts/data_transformation/test.csv
        - artifacts/data_transformation/train.csv
    
    model_training:
      cmd: python src/IRIS_MLops/pipeline/stage04_model_training.py
      deps:
        - src/IRIS_MLops/pipeline/stage04_model_training.py
        - src/IRIS_MLops/pipeline/stage03_data_transformation.py
        - src/IRIS_MLops/pipeline/stage01_data_ingestion.py
      outs:
        - artifacts/model_trainer/model.joblib
  
    model_evaluation:
      cmd: python src/IRIS_MLops/pipeline/stage05_model_evaluation.py
      deps:
        - src/IRIS_MLops/pipeline/stage03_data_transformation.py
        - src/IRIS_MLops/pipeline/stage04_model_training.py
        - src/IRIS_MLops/pipeline/stage05_model_evaluation.py
      outs:
        - artifacts/model_evaluation/metrics.json 